chore: add sync-repo-settings.yaml to grant correct access
googleapis/java-bigquery pull request #738
Opened 2020-09-16 21:03 UTC by stephaniewang526

in order to grant correct access to CODEOWNERS of this repo

2020-09-16 21:37 UTC, chingor13 requested changes

2020-09-16 21:37 UTC, chingor13 commented on .github/sync-repo-settings.yaml
> +- team: @googleapis/api-bigquery
```suggestion
- team: api-bigquery
```

2020-09-16 21:37 UTC, chingor13 commented on .github/sync-repo-settings.yaml
> +  permission: maintain
```suggestion
  permission: write
```

2020-09-16 21:48 UTC, stephaniewang526 commented on .github/sync-repo-settings.yaml
> +  permission: maintain
done

2020-09-17 16:24 UTC, chingor13 approved these changes

2020-09-17 16:28 UTC, chingor13 approved these changes

2020-09-17 16:36 UTC, merged