docs(samples): add query materialized view
googleapis/java-bigquery pull request #978
Opened 2020-11-26 14:28 UTC by pmakani

2020-11-26 14:34 UTC, pmakani commented
Blocked by #977

2020-11-30 19:49 UTC, stephaniewang526 requested changes

2020-11-30 19:49 UTC, stephaniewang526 commented on samples/snippets/src/main/java/com/example/bigquery/QueryMaterializedView.java
> +      Job job = bigquery.create(JobInfo.of(QueryJobConfiguration.of(query)));
Why not just use the `query()` method?

2020-12-01 17:05 UTC, stephaniewang526 approved these changes

2020-12-01 17:05 UTC, merged